import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const sounds = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/sounds' }),
  schema: z.object({
    title: z.string(),
    category: z.string(), // category slug
    tags: z.array(z.string()).default([]),
    duration: z.number(), // seconds
    audio: z.string(), // /audio/{slug}.mp3
    blurb: z.string().min(200), // unique copy — quality gate: ~60-120 words
    origin: z.string().optional(), // one-liner on where the sound comes from
    explainer: z.string().optional(), // path to a blog explainer, e.g. /blog/vine-boom-history/
    added: z.coerce.date(),
    featured: z.boolean().default(false),
    /** Editorial popularity weight used for ordering. NOT a measured play
     *  count — nothing counts plays (see docs). Never display as "plays". */
    plays: z.number().default(0),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/categories' }),
  schema: z.object({
    name: z.string(), // "Meme"
    hubTitle: z.string(), // "Meme Soundboard"
    metaDescription: z.string().max(160),
    intro: z.string().min(400), // ~250 words unique intro
    faq: z
      .array(z.object({ q: z.string(), a: z.string() }))
      .default([]),
    order: z.number().default(99),
  }),
});

/* Themed hubs.
 *
 * Separate from `categories` on purpose. A sound belongs to exactly one
 * category, which is what makes the category grid coherent — but the queries
 * people actually type cut across that. "fnaf soundboard" wants clips filed
 * under gaming AND sound-effects; "goofy ahh soundboard" wants meme, brainrot
 * and spongebob at once. Forcing those into the category system would mean
 * re-filing sounds and breaking the grid to serve a keyword.
 *
 * So a theme gathers sounds by matching slug, title or tag, and nothing has to
 * move. Themes render at the same /{slug}-soundboard/ URL as categories, so
 * slugs must not collide with a category id.
 */
const themes = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/themes' }),
  schema: z.object({
    name: z.string(),
    hubTitle: z.string(),
    metaDescription: z.string().max(160),
    intro: z.string().min(400),
    faq: z.array(z.object({ q: z.string(), a: z.string() })).default([]),
    /** Substrings matched against a sound's slug, title and tags. */
    match: z.array(z.string()).min(1),
    /** Reuses a CategoryIcon key so themes get artwork without new assets. */
    icon: z.string().default('meme'),
    order: z.number().default(99),
    /** Spanish page content. When present, /es/{slug}-soundboard/ renders,
     *  the hreflang pair is emitted on both sides, and the Spanish URL joins
     *  the sitemap — all keyed off this one field, so a theme is either fully
     *  bilingual or fully English, never half-wired. */
    es: z
      .object({
        name: z.string(),
        hubTitle: z.string(),
        metaDescription: z.string().max(160),
        intro: z.string().min(400),
        faq: z.array(z.object({ q: z.string(), a: z.string() })).default([]),
      })
      .optional(),
  }),
});

const blog = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/blog' }),
  schema: z.object({
    title: z.string(),
    /** Optional shorter <title> for search results, when the editorial
     *  headline is longer than the ~60 characters Google will show. The <h1>
     *  always uses `title`, so the page keeps its real headline. */
    seoTitle: z.string().max(60).optional(),
    description: z.string().max(160),
    date: z.coerce.date(),
    updated: z.coerce.date().optional(),
    tags: z.array(z.string()).default([]),
    /** Per-article artwork, 1200x630, generated by scripts/gen-blog-heroes.mjs
     *  into public/blog/{slug}.png. One image does three jobs: the hero on the
     *  article, the thumbnail on /blog/, and og:image when the link is shared.
     *
     *  Optional on purpose. A required field would fail the build the moment
     *  someone drafts a post before running the generator; instead the article
     *  simply renders without a hero and og:image falls back to the sitewide
     *  card in public/og-image.png. The generator warns about any article it
     *  has no artwork for, which is the right place for that complaint. */
    image: z.string().optional(),
    /** Alt text for `image`. Describes the abstract artwork, not the article —
     *  the headline is already adjacent, so repeating it here is noise. */
    imageAlt: z.string().optional(),
  }),
});

export const collections = {
  themes, sounds, categories, blog };
